fragLimit: 25
timeLimit: 15m
bot:
  minPlayers: 3
game:
  motd: "Welcome to Critical Stack"
  type: FreeForAll
  forceRespawn: false
  inactivity: 10m
  #password: "letmein"
  quadFactor: 3
  weaponRespawn: 3
server:
  hostname: "quakekube"
  maxClients: 16
  password: "changeme"
commands:
  - addbot sarge 2
maps:
- name: q3dm7
  type: FreeForAll
  timeLimit: 10m
- name: q3dm17
  type: FreeForAll
- name: q3wctf1
  type: CaptureTheFlag
  captureLimit: 8
- name: q3tourney2
  type: Tournament
- name: q3wctf3
  type: CaptureTheFlag
  captureLimit: 8
- name: ztn3tourney1
  type: Tournament
