fragLimit: 25
timeLimit: 15m
game:
  motd: "Welcome to Critical Stack"
  type: FreeForAll
  forceRespawn: false
  inactivity: 10m
  quadFactor: 3
  weaponRespawn: 3
server:
  hostname: "quakekube"
  maxClients: 12
  password: "changeme"
maps:
- name: q3dm7
  type: FreeForAll
- name: q3dm17
  type: FreeForAll
- name: q3wctf1
  type: CaptureTheFlag
  captureLimit: 8
- name: q3tourney2
  type: Tournament
- name: q3wctf3
  type: CaptureTheFlag
  captureLimit: 8
- name: ztn3tourney1
  type: Tournament
